Repository SW13-Monstera/backend, pull requests merged in 2023-04, with the labels that each got.

#90 refactor : admin test
  src/main/kotlin/io/csbroker/apiserver/auth/LoginUserArgumentResolver.kt
  src/test/kotlin/io/csbroker/apiserver/e2e/AdminControllerMockTest.kt
  src/test/kotlin/io/csbroker/apiserver/e2e/AdminControllerTest.kt
  src/test/kotlin/io/csbroker/apiserver/e2e/RestDocsTest.kt
Labels: bug, documentation, refactor

#91 remove : remove unused standard_answer field
  src/main/kotlin/io/csbroker/apiserver/dto/problem/longproblem/LongProblemUpsertRequestDto.kt
  src/main/kotlin/io/csbroker/apiserver/model/LongProblem.kt
  src/main/kotlin/io/csbroker/apiserver/service/ProblemServiceImpl.kt
  src/test/kotlin/io/csbroker/apiserver/e2e/ProblemApiControllerTest.kt
  src/test/kotlin/io/csbroker/apiserver/e2e/UserControllerTest.kt
Labels: chore

#96 fix : 문제 세트에 속하는 문제 개수를 가져오지 못하던 버그 수정
  src/main/kotlin/io/csbroker/apiserver/model/Problem.kt
  src/main/kotlin/io/csbroker/apiserver/model/ProblemSet.kt
Labels: bug

#97 MSTR-407 : [BE] 리팩토링
  src/main/kotlin/io/csbroker/apiserver/controller/v1/admin/problem/AdminProblemController.kt
  src/main/kotlin/io/csbroker/apiserver/controller/v1/admin/problem/AdminProblemSetController.kt
  src/main/kotlin/io/csbroker/apiserver/controller/v1/problem/LongProblemController.kt
  src/main/kotlin/io/csbroker/apiserver/controller/v1/problem/MultipleProblemController.kt
  src/main/kotlin/io/csbroker/apiserver/controller/v1/problem/ShortProblemController.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/AdminProblemResponseDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/AdminProblemSearchResponseDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/AdminUpsertRequestDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/ProblemDetailResponseDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/ProblemGradingHistoryDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/longproblem/LongProblemDetailResponseDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/longproblem/LongProblemGradingHistoryDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/longproblem/LongProblemResponseDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/longproblem/LongProblemSearchResponseDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/longproblem/LongProblemUpsertRequestDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/multiplechoiceproblem/MultipleChoiceProblemDetailResponseDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/multiplechoiceproblem/MultipleChoiceProblemGradingHistoryDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/multiplechoiceproblem/MultipleChoiceProblemResponseDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/multiplechoiceproblem/MultipleChoiceProblemSearchResponseDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/multiplechoiceproblem/MultipleChoiceProblemUpsertRequestDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/shortproblem/ShortProblemDetailResponseDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/shortproblem/ShortProblemGradingHistoryDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/shortproblem/ShortProblemResponseDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/shortproblem/ShortProblemSearchResponseDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/shortproblem/ShortProblemUpsertRequestDto.kt
  src/test/kotlin/io/csbroker/apiserver/controller/v1/admin/problem/AdminProblemControllerTest.kt
  src/test/kotlin/io/csbroker/apiserver/controller/v1/admin/problem/AdminProblemSetControllerTest.kt
Labels: refactor

#98 refactor : test
  build.gradle.kts
  src/main/kotlin/io/csbroker/apiserver/common/config/security/SecurityConfig.kt
  src/main/kotlin/io/csbroker/apiserver/service/auth/AuthServiceImpl.kt
  src/main/kotlin/io/csbroker/apiserver/service/user/UserServiceImpl.kt
  src/test/kotlin/io/csbroker/apiserver/controller/v1/admin/problem/AdminProblemControllerTest.kt
  src/test/kotlin/io/csbroker/apiserver/controller/v1/admin/problem/AdminUserAnswerProblemControllerTest.kt
  src/test/kotlin/io/csbroker/apiserver/controller/v1/common/AuthControllerTest.kt
  src/test/kotlin/io/csbroker/apiserver/controller/v1/common/NotificationControllerTest.kt
  src/test/kotlin/io/csbroker/apiserver/controller/v2/problem/ProblemControllerV2Test.kt
  src/test/kotlin/io/csbroker/apiserver/service/AuthServiceTest.kt
  src/test/kotlin/io/csbroker/apiserver/service/CustomUserDetailsServiceTest.kt
  src/test/kotlin/io/csbroker/apiserver/service/UserServiceTest.kt
Labels: refactor

#101 20230410 Release
  .github/workflows/ktlint.yml
  build.gradle.kts
  src/main/kotlin/io/csbroker/apiserver/common/config/security/SecurityConfig.kt
  src/main/kotlin/io/csbroker/apiserver/controller/v1/admin/problem/AdminProblemController.kt
  src/main/kotlin/io/csbroker/apiserver/controller/v1/admin/problem/AdminProblemSetController.kt
  src/main/kotlin/io/csbroker/apiserver/controller/v1/problem/LongProblemController.kt
  src/main/kotlin/io/csbroker/apiserver/controller/v1/problem/MultipleProblemController.kt
  src/main/kotlin/io/csbroker/apiserver/controller/v1/problem/ShortProblemController.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/AdminProblemResponseDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/AdminProblemSearchResponseDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/AdminUpsertRequestDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/ProblemDetailResponseDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/ProblemGradingHistoryDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/longproblem/LongProblemDetailResponseDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/longproblem/LongProblemGradingHistoryDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/longproblem/LongProblemResponseDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/longproblem/LongProblemSearchResponseDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/longproblem/LongProblemUpsertRequestDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/multiplechoiceproblem/MultipleChoiceProblemDetailResponseDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/multiplechoiceproblem/MultipleChoiceProblemGradingHistoryDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/multiplechoiceproblem/MultipleChoiceProblemResponseDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/multiplechoiceproblem/MultipleChoiceProblemSearchResponseDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/multiplechoiceproblem/MultipleChoiceProblemUpsertRequestDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/shortproblem/ShortProblemDetailResponseDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/shortproblem/ShortProblemGradingHistoryDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/shortproblem/ShortProblemResponseDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/shortproblem/ShortProblemSearchResponseDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/shortproblem/ShortProblemUpsertRequestDto.kt
  src/main/kotlin/io/csbroker/apiserver/model/Problem.kt
  src/main/kotlin/io/csbroker/apiserver/model/ProblemSet.kt
  src/main/kotlin/io/csbroker/apiserver/service/auth/AuthServiceImpl.kt
  src/main/kotlin/io/csbroker/apiserver/service/user/UserServiceImpl.kt
  src/test/kotlin/io/csbroker/apiserver/controller/v1/admin/problem/AdminProblemControllerTest.kt
  src/test/kotlin/io/csbroker/apiserver/controller/v1/admin/problem/AdminProblemSetControllerTest.kt
  src/test/kotlin/io/csbroker/apiserver/controller/v1/admin/problem/AdminUserAnswerProblemControllerTest.kt
  src/test/kotlin/io/csbroker/apiserver/controller/v1/common/AuthControllerTest.kt
  src/test/kotlin/io/csbroker/apiserver/controller/v1/common/NotificationControllerTest.kt
  src/test/kotlin/io/csbroker/apiserver/controller/v2/problem/ProblemControllerV2Test.kt
  src/test/kotlin/io/csbroker/apiserver/service/AuthServiceTest.kt
  src/test/kotlin/io/csbroker/apiserver/service/CustomUserDetailsServiceTest.kt
  src/test/kotlin/io/csbroker/apiserver/service/UserServiceTest.kt
Labels: release

#102 refactor : unused codes
  src/main/kotlin/io/csbroker/apiserver/auth/AuthToken.kt
  src/main/kotlin/io/csbroker/apiserver/auth/AuthTokenProvider.kt
  src/main/kotlin/io/csbroker/apiserver/common/config/QueryDslConfig.kt
  src/main/kotlin/io/csbroker/apiserver/common/config/security/JwtConfig.kt
  src/main/kotlin/io/csbroker/apiserver/common/config/security/SecurityConfig.kt
  src/main/kotlin/io/csbroker/apiserver/common/filter/RequestWrapper.kt
  src/main/kotlin/io/csbroker/apiserver/common/filter/TokenAuthenticationFilter.kt
  src/main/kotlin/io/csbroker/apiserver/common/handler/OAuth2AuthenticationSuccessHandler.kt
  src/main/kotlin/io/csbroker/apiserver/controller/v1/admin/problem/AdminLongProblemController.kt
  src/main/kotlin/io/csbroker/apiserver/controller/v1/admin/problem/AdminMultipleProblemController.kt
  src/main/kotlin/io/csbroker/apiserver/controller/v1/admin/problem/AdminShortProblemController.kt
  src/main/kotlin/io/csbroker/apiserver/repository/problem/StandardAnswerRepository.kt
  src/main/kotlin/io/csbroker/apiserver/service/auth/AuthServiceImpl.kt
  src/main/kotlin/io/csbroker/apiserver/service/problem/AdminLongProblemServiceImpl.kt
  src/main/kotlin/io/csbroker/apiserver/service/problem/AdminMultipleProblemServiceImpl.kt
  src/main/kotlin/io/csbroker/apiserver/service/problem/AdminShortShortProblemServiceImpl.kt
  src/main/kotlin/io/csbroker/apiserver/service/problem/UserAnswerServiceImpl.kt
Labels: refactor

#100 feat : 문제 랜덤하게 가져오는 로직 추가
  src/docs/asciidoc/index.adoc
  src/main/kotlin/io/csbroker/apiserver/controller/v1/problem/ProblemController.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/ProblemSearchDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/ProblemsResponseDto.kt
  src/main/kotlin/io/csbroker/apiserver/repository/problem/ProblemRepository.kt
  src/main/kotlin/io/csbroker/apiserver/repository/problem/ProblemRepositoryCustom.kt
  src/main/kotlin/io/csbroker/apiserver/repository/problem/ProblemRepositoryCustomImpl.kt
  src/main/kotlin/io/csbroker/apiserver/service/problem/CommonProblemService.kt
  src/main/kotlin/io/csbroker/apiserver/service/problem/CommonProblemServiceImpl.kt
  src/test/kotlin/io/csbroker/apiserver/controller/v1/problem/ProblemControllerTest.kt
Labels: enhancement

#103 feat : 알림을 삭제하는 API 추가
  src/main/kotlin/io/csbroker/apiserver/controller/v1/common/NotificationController.kt
  src/main/kotlin/io/csbroker/apiserver/dto/notification/NotificationBulkDeleteDto.kt
  src/main/kotlin/io/csbroker/apiserver/model/Notification.kt
  src/main/kotlin/io/csbroker/apiserver/repository/common/NotificationRepository.kt
  src/main/kotlin/io/csbroker/apiserver/service/common/NotificationService.kt
  src/main/kotlin/io/csbroker/apiserver/service/common/NotificationServiceImpl.kt
  src/test/kotlin/io/csbroker/apiserver/controller/v1/common/NotificationControllerTest.kt
Labels: documentation, enhancement

#106 fix : standard answer 저장 로직 사라진 것 복구
  src/main/kotlin/io/csbroker/apiserver/repository/problem/StandardAnswerRepository.kt
  src/main/kotlin/io/csbroker/apiserver/service/problem/AdminLongProblemServiceImpl.kt
Labels: bug
