Repository SW13-Monstera/backend, pull requests merged in 2023-11, with the labels that each got.

#142 chore : remove unused codes
  src/main/kotlin/io/csbroker/apiserver/service/auth/AuthService.kt
  src/main/kotlin/io/csbroker/apiserver/service/auth/AuthServiceImpl.kt
  src/main/kotlin/io/csbroker/apiserver/service/post/PostService.kt
  src/main/kotlin/io/csbroker/apiserver/service/post/PostServiceImpl.kt
  src/main/kotlin/io/csbroker/apiserver/service/user/UserService.kt
  src/main/kotlin/io/csbroker/apiserver/service/user/UserServiceImpl.kt
  src/test/kotlin/io/csbroker/apiserver/service/AuthServiceTest.kt
  src/test/kotlin/io/csbroker/apiserver/service/UserServiceTest.kt
Labels: chore

#141 fix : like 테이블 이름 변경 ( like -> likes )
  src/main/kotlin/io/csbroker/apiserver/model/Like.kt
Labels: bug

#143 refactor : getEmailFromSecurityHolder function
  src/main/kotlin/io/csbroker/apiserver/auth/LoginUserArgumentResolver.kt
  src/main/kotlin/io/csbroker/apiserver/common/util/AuthUtil.kt
Labels: refactor

#144 test : Post, Comment 테스트코드 추가 & 버그 fix
  build.gradle.kts
  src/main/kotlin/io/csbroker/apiserver/controller/v1/post/CommentController.kt
  src/main/kotlin/io/csbroker/apiserver/controller/v1/post/response/PostResponseDto.kt
  src/main/kotlin/io/csbroker/apiserver/model/Like.kt
  src/main/kotlin/io/csbroker/apiserver/model/PostLike.kt
  src/main/kotlin/io/csbroker/apiserver/repository/post/PostLikeRepository.kt
  src/main/kotlin/io/csbroker/apiserver/repository/post/PostRepository.kt
  src/main/kotlin/io/csbroker/apiserver/service/post/CommentServiceImpl.kt
  src/main/kotlin/io/csbroker/apiserver/service/post/PostService.kt
  src/main/kotlin/io/csbroker/apiserver/service/post/PostServiceImpl.kt
  src/test/kotlin/io/csbroker/apiserver/controller/v1/post/CommentControllerIntegrationTest.kt
  src/test/kotlin/io/csbroker/apiserver/controller/v1/post/CommentControllerTest.kt
  src/test/kotlin/io/csbroker/apiserver/controller/v1/post/PostControllerIntegrationTest.kt
Labels: test

#145 refactor : ProblemLike -> Like 객체로 변경
  src/main/kotlin/io/csbroker/apiserver/common/enums/LikeType.kt
  src/main/kotlin/io/csbroker/apiserver/model/LongProblem.kt
  src/main/kotlin/io/csbroker/apiserver/model/MultipleChoiceProblem.kt
  src/main/kotlin/io/csbroker/apiserver/model/Problem.kt
  src/main/kotlin/io/csbroker/apiserver/model/ProblemLike.kt
  src/main/kotlin/io/csbroker/apiserver/model/ShortProblem.kt
  src/main/kotlin/io/csbroker/apiserver/repository/post/LikeRepository.kt
  src/main/kotlin/io/csbroker/apiserver/repository/problem/ProblemLikeRepository.kt
  src/main/kotlin/io/csbroker/apiserver/service/post/PostServiceImpl.kt
  src/main/kotlin/io/csbroker/apiserver/service/problem/CommonProblemServiceImpl.kt
  src/main/kotlin/io/csbroker/apiserver/service/problem/LongProblemServiceImpl.kt
  src/main/kotlin/io/csbroker/apiserver/service/problem/MultipleProblemServiceImpl.kt
  src/main/kotlin/io/csbroker/apiserver/service/problem/ShortProblemServiceImpl.kt
  src/test/kotlin/io/csbroker/apiserver/controller/v1/post/PostControllerIntegrationTest.kt
  src/test/kotlin/io/csbroker/apiserver/service/problem/CommonProblemServiceTest.kt
  src/test/kotlin/io/csbroker/apiserver/service/problem/LongProblemServiceTest.kt
  src/test/kotlin/io/csbroker/apiserver/service/problem/MultipleProblemServiceTest.kt
  src/test/kotlin/io/csbroker/apiserver/service/problem/ShortProblemServiceTest.kt
Labels: refactor

#149 fix : oauth 로그인 오류 수정
  src/main/kotlin/io/csbroker/apiserver/common/config/security/SecurityConfig.kt
Labels: bug

#152 chore : github workflow actions version up
  .github/workflows/deploy-prod.yml
  .github/workflows/docs.yml
  .github/workflows/ktlint.yml
  .github/workflows/test.yml
Labels: chore

#155 Release
  src/main/kotlin/io/csbroker/apiserver/service/post/PostServiceImpl.kt
Labels: release
