Repository SW13-Monstera/backend, pull requests merged in 2024-01, with the labels that each got.

#169 refactor : 서술형 채점 코드 삭제
  src/main/kotlin/io/csbroker/apiserver/common/client/AIServerClient.kt
  src/main/kotlin/io/csbroker/apiserver/controller/v1/problem/LongProblemController.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/grade/GradeResultDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/grade/GradingRequestDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/longproblem/ContentDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/longproblem/KeywordDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/longproblem/LongProblemGradingHistoryDto.kt
  src/main/kotlin/io/csbroker/apiserver/service/problem/LongProblemService.kt
  src/main/kotlin/io/csbroker/apiserver/service/problem/LongProblemServiceImpl.kt
  src/test/kotlin/io/csbroker/apiserver/controller/v1/problem/LongProblemControllerTest.kt
  src/test/kotlin/io/csbroker/apiserver/service/problem/LongProblemServiceTest.kt
Labels: refactor

#171 refactor : 안쓰는 코드를 정리 및 리팩터링
  src/main/kotlin/io/csbroker/apiserver/common/enums/ErrorCode.kt
  src/main/kotlin/io/csbroker/apiserver/common/handler/GlobalExceptionHandler.kt
  src/main/kotlin/io/csbroker/apiserver/common/handler/OAuth2AuthenticationFailureHandler.kt
  src/main/kotlin/io/csbroker/apiserver/common/handler/OAuth2AuthenticationSuccessHandler.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/grade/GradingResponseDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/grade/KeywordGradingRequestDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/grade/KeywordGradingResponseDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/grade/LongProblemGradingRequestToAiServerDto.kt
  src/main/kotlin/io/csbroker/apiserver/model/MultipleChoiceProblem.kt
  src/main/kotlin/io/csbroker/apiserver/repository/post/CommentRepository.kt
  src/main/kotlin/io/csbroker/apiserver/service/auth/AuthServiceImpl.kt
  src/main/kotlin/io/csbroker/apiserver/service/problem/admin/AdminMultipleProblemServiceImpl.kt
  src/main/kotlin/io/csbroker/apiserver/service/problem/admin/AdminShortProblemServiceImpl.kt
  src/test/kotlin/io/csbroker/apiserver/ApiServerApplicationTests.kt
  src/test/kotlin/io/csbroker/apiserver/controller/v1/admin/problem/AdminProblemSetControllerTest.kt
  src/test/kotlin/io/csbroker/apiserver/service/problem/ShortProblemServiceTest.kt
  src/test/kotlin/io/csbroker/apiserver/service/problem/admin/AdminMultipleProblemServiceTest.kt
  src/test/kotlin/io/csbroker/apiserver/service/problem/admin/AdminShortProblemServiceTest.kt
  src/test/kotlin/io/csbroker/apiserver/service/problem/admin/TagUpserterTest.kt
Labels: refactor

#173 fix: StandardAnswer 업데이트시 기존 StandardAnswer 삭제 안 되던 버그 수정
  src/main/kotlin/io/csbroker/apiserver/model/LongProblem.kt
  src/main/kotlin/io/csbroker/apiserver/service/problem/admin/AdminLongProblemServiceImpl.kt
  src/test/kotlin/io/csbroker/apiserver/controller/v1/admin/problem/AdminLongProblemControllerIntegrationTest.kt
Labels: bug

#174 refactor: admin 라벨링 코드 제거
  src/docs/asciidoc/index.adoc
  src/main/kotlin/io/csbroker/apiserver/controller/v1/admin/problem/AdminUserAnswerController.kt
  src/main/kotlin/io/csbroker/apiserver/dto/useranswer/AssignUserAnswerDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/useranswer/UserAnswerBatchInsertDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/useranswer/UserAnswerLabelRequestDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/useranswer/UserAnswerResponseDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/useranswer/UserAnswerSearchResponseDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/useranswer/UserAnswerUpsertDto.kt
  src/main/kotlin/io/csbroker/apiserver/model/UserAnswer.kt
  src/main/kotlin/io/csbroker/apiserver/repository/problem/UserAnswerRepository.kt
  src/main/kotlin/io/csbroker/apiserver/repository/problem/UserAnswerRepositoryCustom.kt
  src/main/kotlin/io/csbroker/apiserver/repository/problem/UserAnswerRepositoryCustomImpl.kt
  src/main/kotlin/io/csbroker/apiserver/service/problem/UserAnswerService.kt
  src/main/kotlin/io/csbroker/apiserver/service/problem/UserAnswerServiceImpl.kt
  src/test/kotlin/io/csbroker/apiserver/controller/v1/admin/problem/AdminUserAnswerProblemControllerTest.kt
  src/test/kotlin/io/csbroker/apiserver/service/problem/UserAnswerServiceTest.kt
Labels: refactor

#172 remove : 의미없는 mutable 변수 제거
  src/main/kotlin/io/csbroker/apiserver/auth/GithubOAuth2UserInfo.kt
  src/main/kotlin/io/csbroker/apiserver/auth/GoogleOAuth2UserInfo.kt
  src/main/kotlin/io/csbroker/apiserver/auth/OAuth2UserInfoFactory.kt
  src/main/kotlin/io/csbroker/apiserver/auth/UserPrincipal.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/longproblem/LongProblemUpsertRequestDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/multiplechoiceproblem/MultipleChoiceProblemUpsertRequestDto.kt
  src/main/kotlin/io/csbroker/apiserver/dto/problem/shortproblem/ShortProblemUpsertRequestDto.kt
  src/main/kotlin/io/csbroker/apiserver/service/auth/CustomOAuth2UserService.kt
  src/main/kotlin/io/csbroker/apiserver/service/problem/admin/AdminMultipleProblemServiceImpl.kt
  src/main/kotlin/io/csbroker/apiserver/service/problem/admin/AdminShortProblemServiceImpl.kt
  src/main/kotlin/io/csbroker/apiserver/service/problem/admin/TagUpserter.kt
  src/test/kotlin/io/csbroker/apiserver/controller/v1/admin/problem/AdminLongProblemControllerTest.kt
  src/test/kotlin/io/csbroker/apiserver/controller/v1/admin/problem/AdminMultipleProblemControllerTest.kt
  src/test/kotlin/io/csbroker/apiserver/controller/v1/admin/problem/AdminMultipleProblemIntegrationTest.kt
  src/test/kotlin/io/csbroker/apiserver/controller/v1/admin/problem/AdminProblemControllerTest.kt
  src/test/kotlin/io/csbroker/apiserver/controller/v1/admin/problem/AdminShortProblemControllerTest.kt
  src/test/kotlin/io/csbroker/apiserver/service/problem/admin/AdminLongProblemServiceTest.kt
  src/test/kotlin/io/csbroker/apiserver/service/problem/admin/AdminMultipleProblemServiceTest.kt
  src/test/kotlin/io/csbroker/apiserver/service/problem/admin/AdminShortProblemServiceTest.kt
  src/test/kotlin/io/csbroker/apiserver/service/problem/admin/TagUpserterTest.kt
Labels: refactor

#175 Feature/fix tag bug
  src/main/kotlin/io/csbroker/apiserver/common/enums/ErrorCode.kt
  src/main/kotlin/io/csbroker/apiserver/model/Problem.kt
  src/main/kotlin/io/csbroker/apiserver/model/Tag.kt
  src/main/kotlin/io/csbroker/apiserver/repository/problem/ProblemTagRepository.kt
  src/main/kotlin/io/csbroker/apiserver/service/problem/admin/AdminLongProblemServiceImpl.kt
  src/main/kotlin/io/csbroker/apiserver/service/problem/admin/TagUpserter.kt
  src/test/kotlin/io/csbroker/apiserver/controller/v1/admin/problem/AdminLongProblemControllerIntegrationTest.kt
  src/test/kotlin/io/csbroker/apiserver/controller/v1/admin/problem/AdminMultipleProblemIntegrationTest.kt
  src/test/kotlin/io/csbroker/apiserver/service/problem/admin/TagUpserterTest.kt
Labels: bug, refactor
